# Generated by Django 5.2.7 on 2025-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprendices',
            fields=[
                ('id_aprendiz', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aprendices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AprendizFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aprendiz_ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_registro', models.DateTimeField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id_caracterizacion', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('trimestre', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'caracterizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoComunicacion',
            fields=[
                ('id_consentimiento', models.AutoField(primary_key=True, serialize=False)),
                ('medio', models.CharField(max_length=50)),
                ('aceptado', models.BooleanField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'consentimiento_comunicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convocatorias',
            fields=[
                ('id_convocatorias', models.AutoField(primary_key=True, serialize=False)),
                ('con_nombre', models.CharField(max_length=150)),
                ('con_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('con_cant_beneficiario', models.IntegerField(blank=True, null=True)),
                ('con_fecha_inicio', models.DateField(blank=True, null=True)),
                ('con_fecha_creacion', models.DateField(blank=True, null=True)),
                ('con_documento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'convocatorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EncuestasAprendices',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'encuestas_aprendices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ficha', models.CharField(max_length=20, unique=True)),
                ('jornada', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionariosBienestar',
            fields=[
                ('id_funcionario_b', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'funcionarios_bienestar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instructores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('tipo', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('estado', models.TextField()),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('post_fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntasCaracterizacion',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pregunta', models.CharField(blank=True, max_length=50, null=True)),
                ('obligatoria', models.BooleanField(blank=True, null=True)),
                ('pregunta', models.TextField()),
            ],
            options={
                'db_table': 'preguntas_caracterizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntasEncuestas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'preguntas_encuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramasFormacion',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.TextField()),
                ('duracion_meses', models.SmallIntegerField()),
                ('modalidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'programas_formacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('generado_por', models.TextField()),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportesAcademicos',
            fields=[
                ('id_reporte_academico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'reportes_academicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestasCaracterizacion',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuestas_caracterizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestasEncuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField()),
            ],
            options={
                'db_table': 'respuestas_encuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultadopostulacion',
            fields=[
                ('id_resultadopostulacion', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.TextField()),
                ('res_valoracion', models.CharField(blank=True, max_length=100, null=True)),
                ('res_resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('res_fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultadopostulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nivel', models.TextField()),
                ('generado_por', models.TextField()),
            ],
            options={
                'db_table': 'riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('qr_codigo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sesion_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoConvocatorias',
            fields=[
                ('id_tipo_convocatorias', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_convocatorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.TextField()),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
                ('contrasenia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
