# Generated by Django 5.2.7 on 2025-10-17 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0002_alter_aprendiz_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_nombre', models.CharField(max_length=200)),
                ('con_cantidad_beneficiarios', models.IntegerField()),
                ('con_fecha_inicio', models.DateTimeField()),
                ('con_fecha_final', models.DateTimeField()),
                ('con_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('con_documento', models.FileField(blank=True, null=True, upload_to='convocatorias/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_fecha_hora_postulacion', models.DateTimeField(auto_now_add=True)),
                ('pos_aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('pos_convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_valoracion', models.IntegerField()),
                ('res_resultado', models.CharField(choices=[('Beneficiado', 'Beneficiado'), ('No Beneficiado', 'No Beneficiado')], default=None, max_length=16, null=True)),
                ('res_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('res_postulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.postulacion')),
            ],
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='con_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.tipoconvocatoria'),
        ),
    ]
