# Generated by Django 5.2.7 on 2025-10-17 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0003_convocatoria_tipoconvocatoria_postulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('es_plantilla_inicial', models.BooleanField(default=False, help_text='Esta es la plantilla para nuevos registros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Caracterización',
                'verbose_name_plural': 'Plantillas de Caracterización',
            },
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='apellidos_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='documento_temp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='email_temp',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_registro_caracterizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='nombres_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='telefono_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='usuario_creado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_ingreso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_solicitante', models.CharField(blank=True, max_length=30, null=True)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_solicitante', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.IntegerField(help_text='Año de la caracterización (ej: 2024)')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3'), ('T4', 'Trimestre 4'), ('T5', 'Trimestre 5'), ('T6', 'Trimestre 6'), ('T7', 'Trimestre 7'), ('T8', 'Trimestre 8')], help_text='Trimestre en el que se realiza', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('completada', models.BooleanField(default=False)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('fecha_aceptacion_terminos', models.DateTimeField(blank=True, null=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario_creado_desde_caracterizacion', models.BooleanField(default=False)),
                ('id_aprendiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracterizaciones', to='appAvanser.aprendiz')),
            ],
            options={
                'verbose_name': 'Caracterización',
                'verbose_name_plural': 'Caracterizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(help_text='Texto de la pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('texto', 'Texto Libre'), ('seleccion_simple', 'Selección Simple'), ('seleccion_multiple', 'Selección Múltiple'), ('si_no', 'Sí/No'), ('numero', 'Numérico'), ('fecha', 'Fecha'), ('escala', 'Escala (1-5)')], default='texto', max_length=20)),
                ('obligatoria', models.BooleanField(default=False, help_text='Si es obligatoria, el aprendiz debe responderla')),
                ('opciones', models.JSONField(blank=True, help_text="Opciones para preguntas de selección. Ej: ['Opción 1', 'Opción 2']", null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición de la pregunta')),
                ('id_caracterizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='appAvanser.caracterizacion')),
            ],
            options={
                'verbose_name': 'Pregunta de Caracterización',
                'verbose_name_plural': 'Preguntas de Caracterización',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('datos_personales', 'Datos Personales'), ('datos_academicos', 'Datos Académicos'), ('datos_socioeconomicos', 'Datos Socioeconómicos'), ('datos_salud', 'Datos de Salud'), ('datos_bienestar', 'Datos de Bienestar')], max_length=50)),
                ('pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('texto', 'Texto Libre'), ('email', 'Correo Electrónico'), ('telefono', 'Teléfono'), ('documento', 'Número de Documento'), ('seleccion_simple', 'Selección Simple'), ('seleccion_multiple', 'Selección Múltiple'), ('si_no', 'Sí/No'), ('numero', 'Numérico'), ('fecha', 'Fecha'), ('escala', 'Escala (1-5)')], max_length=20)),
                ('obligatoria', models.BooleanField(default=False)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('ayuda', models.TextField(blank=True, help_text='Texto de ayuda para la pregunta')),
                ('campo_usuario', models.CharField(blank=True, help_text="Campo del modelo Usuario que se llena con esta respuesta (ej: 'first_name', 'email')", max_length=50, null=True)),
                ('campo_aprendiz', models.CharField(blank=True, help_text='Campo del modelo Aprendiz que se llena con esta respuesta', max_length=50, null=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_plantilla', to='appAvanser.plantillacaracterizacion')),
            ],
            options={
                'verbose_name': 'Pregunta de Plantilla',
                'verbose_name_plural': 'Preguntas de Plantilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta del aprendiz', null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
                ('id_caracterizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='appAvanser.caracterizacion')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='appAvanser.preguntacaracterizacion')),
            ],
            options={
                'verbose_name': 'Respuesta de Caracterización',
                'verbose_name_plural': 'Respuestas de Caracterización',
                'unique_together': {('id_caracterizacion', 'id_pregunta')},
            },
        ),
    ]
