# Generated by Django 5.2.7 on 2025-10-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0004_plantillacaracterizacion_aprendiz_apellidos_temp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadopostulacion',
            name='res_postulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_postulacion', to='appAvanser.postulacion'),
        ),
    ]
