# Generated by Django 5.2.7 on 2025-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0005_alter_resultadopostulacion_res_postulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='competencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
