# Generated by Django 5.2.7 on 2025-10-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0006_instructor_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadorinstructores',
            name='tambien_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='es_coordinador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles_extra',
            field=models.JSONField(blank=True, help_text="Lista de roles adicionales si el usuario cumple más de una función (ej: ['instructor', 'coordinadorInstructores'])", null=True),
        ),
    ]
