# Generated by Django 5.2.7 on 2025-10-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('cant_beneficiarios', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, unique=True)),
                ('jornada', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('duracion_meses', models.PositiveSmallIntegerField()),
                ('modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('trimestre', models.SmallIntegerField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimientoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(max_length=50)),
                ('aceptado', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='AprendizFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pregunta', models.CharField(max_length=50)),
                ('obligatoria', models.BooleanField(default=False)),
                ('pregunta', models.TextField()),
                ('caracterizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.caracterizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.encuestaaprendiz')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.programaformacion'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('generado_por', models.CharField(max_length=100)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.preguntacaracterizacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField()),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.preguntaencuesta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=50)),
                ('valoracion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.postulacion')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(max_length=50)),
                ('generado_por', models.CharField(max_length=100)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
            ],
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('qr_codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.sesionclase')),
            ],
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='tipo_convocatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.tipoconvocatoria'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PP', 'Pasaporte'), ('RC', 'Registro civil')], max_length=2)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('contrasenia', models.CharField(max_length=128)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAvanser.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_cargue', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_trimestrales', to='appAvanser.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_subidos', to='appAvanser.usuario')),
            ],
            options={
                'verbose_name': 'Reporte Trimestral',
                'verbose_name_plural': 'Reportes Trimestrales',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('mensaje', 'Mensaje'), ('info', 'Información')], default='mensaje', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='appAvanser.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario'),
        ),
        migrations.CreateModel(
            name='FuncionarioBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CitaComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_comite', to='appAvanser.usuario')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to='appAvanser.usuario')),
                ('otros_invitados', models.ManyToManyField(blank=True, related_name='citas_invitado', to='appAvanser.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('estado', models.CharField(choices=[('sin_revisar', 'Sin revisar'), ('aprobado', 'Aprobado'), ('aun_no_aprobado', 'Aún no aprobado'), ('no_aprobado', 'No aprobado')], default='sin_revisar', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('plazo_extra', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_asignadas', to='appAvanser.usuario')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_creadas', to='appAvanser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('deshabilitada', 'Deshabilitada')], default='activa', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='appAvanser.ficha')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_asignadas', to='appAvanser.usuario')),
            ],
            options={
                'unique_together': {('instructor', 'ficha')},
            },
        ),
    ]
